src/common/lib/metamask/index.js
src/common/lib/wallet.js
src/core/components/ui/WalletBinding/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-627?atlOrigin=eyJpIjoiZTI0MDVlMzBkMmY5NDJlMDkxY2ViN2M0MDg2YzYxNjMiLCJwIjoiaiJ9
- https://blocksphere2020.atlassian.net/browse/DBIO-628?atlOrigin=eyJpIjoiOGM0Y2Y5NDY0ZDllNDg5MTg1OTVmN2MyZTY5ZjAwZmIiLCJwIjoiaiJ9
- Create connect to metamask dialog
- Create wallet information dialog

Feat: wallet information component

---

.debio.pipeline.yml

- https://blocksphere2020.atlassian.net/browse/DBIO-646
- Setup CI in Drone for Testing new repo

fix: removed unneccessary build process

---

.debio.pipeline.yml

- https://blocksphere2020.atlassian.net/browse/DBIO-646
- Setup CI in Drone for Testing new repo

fix: deployment pipeline.

---

.github/pull_request_template.md

- create pull request template

[ Github ] Update pull request template

---

src/common/components/DataTable/index.vue
src/styles/variables.scss

[https://blocksphere2020.atlassian.net/browse/DBIO-618](url)
Create Table component

[Feat] Revamp FrontEnd : Table

---

src/common/components/Dialog/index.vue
src/common/lib/categories.js
src/common/lib/location.js
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
src/views/Dashboard/Customer/Home/RequestTest/RequestTestCheckout/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/RequestTestCheckout/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/RequestTestCheckout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
src/views/Dashboard/Customer/Home/RequestTest/RequestTestNav.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectLab/AgreementDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectLab/NoLab.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectLab/ServiceDetailDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectLab/index.vue
src/views/Dashboard/Customer/Home/RequestTest/Success/index.vue
src/views/Dashboard/Customer/Home/RequestTest/index.vue
src/views/Dashboard/Customer/Home/index.vue
src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-693
-  https://blocksphere2020.atlassian.net/browse/DBIO-694
- https://blocksphere2020.atlassian.net/browse/DBIO-767
- Create Request Test Page
- Create Select Lab Page
- Create Request Test Flow when  no available lab
- Get Category from BE
-

enhance request test flow

---

src/common/components/Navbar.vue
src/common/components/WalletBinding.vue
src/store/index.js
src/store/wallet.js

- https://blocksphere2020.atlassian.net/browse/DBIO-627
- Fix closeDialog
- Connect wallet-binding to backend
-

fix wallet binding

---

.debio.pipeline.yml

- https://blocksphere2020.atlassian.net/browse/DBIO-819
- Added Telegram notification on the Drone pipeline.

ci: added telegram notification for drone pipeline.

---

.debio.pipeline.yml

- https://blocksphere2020.atlassian.net/browse/DBIO-819
- Changed stage name and removed duplicate secrets.

ci: changed stage name and removed duplicate secrets.

---

src/common/components/Navbar.vue
src/common/lib/route-guard.js
src/router/routes/index.js
src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
src/views/LandingPage/SignIn/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-839
- Remove Select Role after Sign In and redirect to Customer
- Remove Switch Account in Navbar
-

remove select role and take out switch role

---

src/router/routes/customer.js
src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-789
- MInor update active state
-

fix: active state sidebar

---

src/router/routes/customer.js
src/views/Dashboard/Customer/Home/Emr/Details.vue

- N/A
- Minor Updates route and EMR details
-

fix: Minor updates routes

---

src/common/components/Navbar.vue

feat: fetch wallets

---

src/common/lib/labs.js
src/store/lab.js
src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-914
- Change labs api endpoint parameter to query

update: change labs-api endpoint parameter to query

---

src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-872
- Add filter for verified labs

feat: add filter for verified labs

---

src/router/routes/signIn.js
src/views/LandingPage/GenerateAccount/index.vue
src/views/LandingPage/SignIn/ForgotPassword.vue
src/views/LandingPage/SignIn/InputMnemonic.vue
src/views/LandingPage/SignIn/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-972
- https://blocksphere2020.atlassian.net/browse/DBIO-973
- Remove KeyStore Option
- Add function for sign-in
- Add condition to check local storage when signin and create page to input mnemonic

feat: enhance sign-in flow

---

.eslintrc.js
Dockerfile
package.json

ci: fix Dockerfile

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/mlc_config.json
.github/workflows/publish-draft-release-candidate.yml
.github/workflows/publish-draft-release.yml
.github/workflows/pull-request.yml
.github/workflows/rcb_config.json
.github/workflows/release-candidate.yml
.github/workflows/release.yml
.maintain/Dockerfile

ci: added github action workflow
- add [pull request, main, beta, alpha, release candidate, publish draft release, release] automation

[DBIO-879 & DBIO-742] ci: add github action workflow

---

src/common/icons/index.js

- N/A
Error when running the build, then this comes up:
- Build fix

fix: build.

---

src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue

- N/A
- Update dummy status to dynamic by specimen
-

fix: test status and validation

---

src/views/Dashboard/Customer/Home/Emr/Create.vue

- N/A
- Fix error in EMR create
- N/A
- N/A

fix: fix double quotes

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

ci: remove unused env

---

.github/workflows/main.yml

ci: fix image tag dev environment

ci: fix image tag dev environment

---

src/views/LandingPage/GenerateAccount/index.vue

- N/A
- Update Terms & Conditions and Privacy Policy links
- N/A

fix: update terms & conditions and privacy policy links

---

src/common/components/Navbar.vue
src/common/components/WalletBinding.vue
src/common/lib/metamask/wallet.js

- N/A
- Fix Dai Balance in metamask wallet
- N/A

fix: fix dai balance

---

src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1048
- Add password validation on mounted (to get mnemonic decrypt value)
-

feat: Add input password on mounted

---

src/views/LandingPage/SignIn/ChangePassword.vue
src/views/LandingPage/SignIn/index.vue

- [https://blocksphere2020.atlassian.net/browse/DBIO-710](url)
- add validation for sign in
-

Password validation

---

src/common/components/Rating/index.vue
src/common/icons/index.js
src/common/lib/rating.js
src/views/Dashboard/Customer/Home/MyTest/TestResult.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-987
- wiring ipfs
- submit rating
- rename component name to uiDebioRating
- add rating.js file to handle submit rating
- comma in icons/index.js
-

Test result

---

Dockerfile

ci: update Dockerfile

---

package-lock.json
src/common/components/Card/index.vue
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/MyTest/dataTesting.json
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/index.vue

- 
- add action navigate route on button component
- Add styles z-index on global card component 
- change style on table
-

fix: fix button clicked route

---

src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue

- https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1030&assignee=6087b822248ef6007372dab6
- changed service and lab icon to image
-

fix: test summary

---

.github/workflows/main.yml

ci: fix vault env

---

.github/workflows/main.yml

ci: fix create labs.js

---

src/common/components/NavigationDrawer.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1082
- Fix navigation drawer issue
- @luthfiazhari please don't use `push` in the future for navigation/reusable route
-

fix: Redundant navigation drawer issue

---

src/common/components/Banner/index.vue
src/common/lib/polkadot-provider/command/electronic-medical-record.js
src/views/Dashboard/Customer/Home/Emr/Details.vue
src/views/Dashboard/Customer/Home/Emr/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-695
- Update EMR listing data from the substrate
-

feat: update EMR listing from substrate

---

src/common/components/Navbar.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1097
- Fix navbar signout typo to Sign Out
-

fix: Navbar signout typo to Sign Out

---

src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

-  Checkout from payment history flow

fix: checkout from payment history

---

src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/index.vue

- N/A
- Fix delete error on EMR Page
-

fix: Delete emr documents

---

src/common/lib/polkadot-provider/command/service-request.js
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue

- N/a
- Wiring Create Request service staking to substrate
- N/a

feat: wiring createRequest

---

package-lock.json
src/views/Dashboard/Customer/Home/index.vue

- 
- change image on detail order table from component to link ipfs.
- fix typo wording variable
-

fix: fix image from component to link on dashboard page

---

src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1127
- https://blocksphere2020.atlassian.net/browse/DBIO-1128
- Fix password issue
- Add icon on the password field
- Update ellipsis text file name
-

fix: Password allways error and fix length file name

---

src/common/components/Input/index.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1131
- Minor update payment history wording title
- Minor update input placeholder word limitations
-

fix: Minor update mismatch title and input placeholder limit

---

src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
src/views/LandingPage/GenerateAccount/index.vue
src/views/LandingPage/LandingPagePopUp.vue

- https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1111&assignee=6087b822248ef6007372dab6
- https://blocksphere2020.atlassian.net/jira/software/c/projects/DBIO/boards/14?modal=detail&selectedIssue=DBIO-1093&assignee=6087b822248ef6007372dab6
- grey out button in request test form before all field is filled
- fixed the component style in landing page -> generate account
-

fix: form validation and component style

---

src/common/components/Navbar.vue
src/common/components/WalletBinding.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1094
- fix closse button in wallet binding

fix: close button in wallet binding

---

src/common/components/Dialog/ConfirmationDialog.vue
src/common/constants/staking-status.js
src/common/lib/service-request.js
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/MyTest/stakingData.json

- https://blocksphere2020.atlassian.net/browse/DBIO-786
- enhance unstake request service
- n/a

feat: enhance unstake request service

---

.github/workflows/alpha.yml

ci: improve deployment env secret

---

.maintain/docker/Dockerfile

ci: improve Dockerfile

---

src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1101
- https://blocksphere2020.atlassian.net/browse/DBIO-1102
- fix mismatch lab-image
- fix duration type
- add city and country to detail address
- fix layout rating and count rate
- fix mismatch in detail card

fix: service detail mismatch

---

src/common/components/Navbar.vue
src/common/lib/balance-format.js
src/common/lib/polkadot-provider/query/balance.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1149
- https://blocksphere2020.atlassian.net/browse/DBIO-1095
- Add condition to check metamask address
- Add function to format balances

add format from/to ether

---

src/common/components/DataTable/index.vue

- [https://blocksphere2020.atlassian.net/browse/DBIO-1107](url)
- fix error on data table component, create computed data for default error.
-

fix: fix error function on table component

---

src/App.vue
src/views/Dashboard/Customer/Home/Emr/index.vue
src/views/NoAccessMobile.vue

- N/A
- Update device width validation
-

fix: minor update no access

---

src/common/components/Dropdown/index.vue
src/common/components/File/index.vue
src/common/components/Input/index.vue
src/common/components/Textarea/index.vue
src/common/lib/validate/validateForms.js
src/common/lib/validate/validateInput.js
src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1123
- 
-

fix: Remove icon and label color when got error

---

src/common/lib/metamask/escrow.js
src/common/lib/polkadot-provider/command/orders.js
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1104 
- Adjust prices from/to ether format
- Fix bugs in payment history to checkout
- Fix button when order paid

fix: bugs payment

---

.maintain/docker/Dockerfile
Dockerfile
nginx/conf.d/default.conf

ci: fix refresh 404

---

src/common/components/NavigationDrawer.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue

- [https://blocksphere2020.atlassian.net/browse/DBIO-1106](url)
- 
-

fix: fix styling table on MyTest page

---

src/common/components/Icon/index.vue
src/common/components/Navbar.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1176
- Create notification indicator
-

feat: Notification dot indicator

---

src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1190
- add link to view instructions in checkout payment page
- fix layout in checkout payment page

fix: checkout payment page

---

src/common/components/Icon/index.vue
src/common/components/NavigationDrawer.vue
src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1211
- Update layout debio customer ui 
-

fix: Layouting padding, possition issue

---

src/App.vue
src/common/components/Navbar.vue
src/views/Dashboard/Customer/Layout.vue

- N/A
- Fix navbar hover issue
- Update safari no access from mobile validation
- Update notif "read" on click
-

fix: Navbar hover issue

---

src/views/Dashboard/Customer/Home/index.vue

- [https://blocksphere2020.atlassian.net/browse/DBIO-1026](url)
- fix minor typos on dashboard customer
-

fix: fix minor typos on dashboard customer

---

src/router/routes/index.js

fix: customer routes

---

src/router/routes/index.js
src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue

- Link to Etherscan
- Price in Lab Detail Card

fix: link to etherscan

---

src/common/components/Dialog/CancelDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1216
- Fix wording in cancel dialog and checkout page

fix: fix cancel order

---

src/common/lib/error-handler.js
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1144
- Add Error Handler

feat: add error handler

---

src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
src/views/Dashboard/Customer/Home/MyTest/TestResult.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/index.vue

- [https://blocksphere2020.atlassian.net/browse/DBIO-1215](url)
-

refactor: refactor code for fetch result history data

---

src/views/Dashboard/Customer/Home/DataBounty/index.vue
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1273
- Update validation button details
- Add link to data sample
- Remove dummy data bounty
-

fix: Button unpaid and remove dummy data bounty

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue

fix: adjust date format

---

src/views/Dashboard/Customer/Home/Emr/index.vue
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

- N/A
- Update date standard formating
- Update validation payment checkout
-

fix: Some bug and update date formating to our standard

---

src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

- N/A
- Fix payment history currency formating
-

fix: Currency formating

---

src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue

- none urgent change
- fix bug on myTest function for fetch data from substrate
- fix bug params on orderHistoryPage for swith banner and steper base on speciments status
-

fix: fix bug function on myTest page

---

src/common/lib/polkadot-provider/events/handlers/customer.js
src/store/substrate/event-types.json
src/store/substrate/index.js

- N/A
- Minor fix wallet binding notification
-

fix: Notification wallet binding

---

src/views/Dashboard/Customer/Home/PaymentHistory/index.vue

- N/A
- Minor update date formating
-

fix: Payment history date formating

---

src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue

- N/A
- Fix databounty payload
-

fix: Quick fix my test and bounty error

---

package.json
src/common/components/Dialog/ConfirmationDialog.vue
src/common/lib/polkadot-provider/command/service-request.js
src/router/routes/index.js
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1096
- add params in my-test route
- change title to DeBio
- change wording in success dialog after create service

fix: directing to stake service tab

---

src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- N/a
- Implement rating in cards by use ui-debio-rating

fix: use ui-debio-rating for show rate in cards

---

src/common/lib/metamask/escrow.js
src/common/lib/polkadot-provider/query/balance.js
src/common/lib/polkadot-provider/query/orders.js
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1288
- Fix bugs payment to escrow
- Add validation when DAI is less than total price
- N/a

fix: fix bugs payment to escrow

---

src/common/lib/categories.js
src/common/lib/debio-balance.js
src/common/lib/emr.js
src/common/lib/ipfs/gcs.js
src/common/lib/labs.js
src/common/lib/location.js
src/common/lib/orders.js
src/common/lib/rating.js
src/common/lib/service-request.js
src/store/auth.js
src/store/rating.js
src/store/wallet.js
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/LandingPage/GenerateAccount/SetPassword.vue
src/views/LandingPage/SignIn/ChangePassword.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1325
- Update name `ENV` (Remove `DEV` prefix)
- Fix my test layouting
- Update logic on how to use ENV
- Please @ciniiia @luthfiazhari @hilyds @meziaris @agustinustheo update your ENV to the latest update because it's will break changes

refactor: Update name and how to use ENV

---

src/common/lib/polkadot-provider/command/info.js
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1103
- https://blocksphere2020.atlassian.net/browse/DBIO-1188
- Fix typos in payment receipt
- Add transacition weight in payment receipt dialog

fix: adjust payment receipt

---

src/common/lib/polkadot-provider/events/handlers/customer.js
src/store/substrate/event-types.json
src/views/Dashboard/Customer/Home/Emr/Create.vue

- N/A
- Fix EMR edit the double file
- Update wording notification
-

fix: EMR edit and update notification wording

---

src/common/lib/validate/validateForms.js
src/views/Dashboard/Customer/Home/Emr/Create.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1340
- Fix stuck error on EMR popup
-

fix: Stuck error

---

src/common/components/Dialog/CancelDialog.vue
src/common/components/Dialog/ErrorDialog.vue
src/common/components/Stepper/index.vue
src/common/styles/mixins.sass
src/views/Dashboard/Customer/Home/DataBounty/index.vue
src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectLocation.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/Success/PaymentSuccess.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1251
- adjust mixins

fix: adjust-style-mixins

---

src/common/lib/polkadot-provider/command/info.js
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
src/views/LandingPage/SignIn/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1277
- https://blocksphere2020.atlassian.net/browse/DBIO-1347
- https://blocksphere2020.atlassian.net/browse/DBIO-1357
- Remove checkbox in staking pop up
- Adjust wording
- Change button from continue to stake
- Add transaction weight
- Add validation in input (amount must be number or decimal with (.) & amount is required ) 
- Add validation balance must be more than staking amount and transaction weight
- Show error insufficient amount if balance is less than staking amount and transaction weight
- I used mixins from https://github.com/debionetwork/debio-customer-ui/pull/190
- N/a

fix: request staking

---

src/common/components/Dialog/index.vue
src/common/lib/error-handler.js
src/store/substrate/event-types.json
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1348
- https://blocksphere2020.atlassian.net/browse/DBIO-1358
- Remove transfer in notif
- Fix loading in create staking
- Adjust new success pop up as in figma
- Add condition in error 
- Adjust operation tag in payment card and dialog
- N/A
- N/A

Bugs create staking

---

src/common/components/DataTable/index.vue
src/common/styles/mixins.sass
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/index.vue

- [https://blocksphere2020.atlassian.net/browse/DBIO-1326](url)
- [https://blocksphere2020.atlassian.net/browse/DBIO-1252](url)
- change styling mytest page acording to figma
- adjust mixins
-

chore: styling

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

- https://blocksphere2020.atlassian.net/browse/DBIO-1386
- add new env
- fix mainnet secret env

ci: add new env and fix mainnet secret

---

src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Details.vue

- N/A
- Fix IPFS data undefined if file edited
-

fix: IPFS data undefined if file edited

---

src/common/lib/api/gcs.js
src/common/lib/api/index.js
src/common/lib/api/rating.js
src/store/wallet.js
src/views/LandingPage/GenerateAccount/SetPassword.vue
src/views/LandingPage/GenerateAccount/index.vue
src/views/LandingPage/SignIn/ChangePassword.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1306
- Store TERMS on local storage
- Update auth to general (GET and POST)
-

feat: Store Terms on local storage and update auth to general

---

src/common/components/Dialog/ErrorDialog.vue
src/common/lib/polkadot-provider/events/handlers/customer.js
src/store/substrate/event-types.json
src/store/substrate/index.js
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue

- n/a
- add notification in service request
- fix typo in dismiss button
- fix event listening to ServiceRequestCreated when create request and ServiceRequestWaitingForUnstaked when unstaking
- n/a
- n/a

feat: add request service notification in event config

---

package-lock.json
package.json
src/common/components/Dialog/ConfirmationDialog.vue
src/common/lib/api/service-request.js
src/main.js
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/index.vue
src/views/LandingPage/Layout.vue
src/views/LandingPage/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1373
- Change wording in landing page
- Update unstake pop up
- Fix countdown timer
-

fix: fix layout unstake

---

package-lock.json
package.json
src/common/lib/api/categories.js
src/common/lib/api/labs.js
src/common/lib/api/location.js
src/common/lib/api/rating.js
src/store/lab.js
src/store/rating.js
src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/Success/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1260
- https://blocksphere2020.atlassian.net/browse/DBIO-1342
- https://blocksphere2020.atlassian.net/browse/DBIO-1327
- Add size and page in get /service-request
- Remove handleBack in success page
- Add loading page

fix: adjust api with auth

---

src/store/substrate/index.js

- N/A
- Remove the console from the substrate
-

fix: Remove console from substrate

---

src/common/components/Dialog/ConfirmationDialog.vue
src/common/lib/polkadot-provider/command/info.js
src/views/Dashboard/Customer/Home/MyTest/index.vue

- n/a
- add tx weight in unstake pop up
- n/a
-n/a

add-tx-weight

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

ci: fix image repository

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/release.yml

ci: fix image tag

---

src/common/components/Banner/index.vue
src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/index.vue
src/views/Dashboard/Customer/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1210
- https://blocksphere2020.atlassian.net/browse/DBIO-1267
- Minor update wording dashboard
- Update max length emr char title and document
-

fix: Several minor issue on EMR page

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

N/A
ci: improve high availability

ci: improve high availability

---

.github/workflows/beta.yml
.github/workflows/release.yml

ci: fix secret

---

package-lock.json
package.json
src/common/lib/api/index.js
src/main.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1422
- Setup app analytics with Mixpanel.
- Sentry for crashlytics.
- Must add `VUE_APP_SENTRY_DSN` and `VUE_APP_MIXPANEL_TOKEN` environment variable, accessible here: https://blocksphere2020.atlassian.net/wiki/spaces/DBIO/pages/33063034/Frontend+ENV

feat: mixpanel and sentry analytics.

---

src/common/components/Dialog/ConfirmationDialog.vue
src/common/lib/api/debio-balance.js
src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/index.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1382
- change endpoint to /conversion/cache
- remove unused lines
- fix some minor bugs and layout styling
- n/a
- n/a

fix: staking amount not showing

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1503
- adjust data table, when item is empty
- n/a
-n/a

[DBIO-1503] fix: list of staking service not show in stake service tab

---

src/common/constants/error-messages.js
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
src/views/LandingPage/GenerateAccount/SetPassword.vue
src/views/LandingPage/SignIn/ChangePassword.vue
src/views/LandingPage/SignIn/InputMnemonic.vue
src/views/LandingPage/SignIn/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1315
- Implement error messages to sign in , request test , and staking service pages
- n/a
- n/a

[DBIO-1315] feat: adapt error message to pages

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

- N/A
- ci: improve resources requests of deployments
-

ci: improve resources requests of deployments

---

src/common/components/Avatar/index.vue
tests/unit/common/components/avatar.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1468
- Unit testing 
- Update some logic on avatar component
-

[DBIO-1468] tests: unit testing and update some logic on avatar component.

---

src/common/components/Modal/index.vue
tests/unit/common/components/modal.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1475
- Add unit testing
-

[DBIO-1475] tests: modal unit testing.

---

src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1456
- Add forgot password on the modal password input
-

[DBIO-1456] feat: forgot password

---

.github/pull_request_template.md

docs: pull_request_template.md

---

src/common/lib/polkadot-provider/events/handlers/customer.js
src/store/substrate/event-types.json
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- 
- Add new customer notification
- Fix validate my test tabs page
- Fix Missmatch path
-

fix: customer notifications

---

.github/workflows/alpha.yml
.github/workflows/beta.yml
.github/workflows/main.yml
.github/workflows/release.yml

Add new env

---

tests/unit/common/components/button.spec.js

- [https://blocksphere2020.atlassian.net/browse/DBIO-1464](url)
- create unit testing button component
-

[DBIO-1464] Unit Testing Component Button

---

src/common/components/NavigationDrawer.vue

- [https://blocksphere2020.atlassian.net/browse/DBIO-781](url)
- fix: delete border on navigation drawer
-

[DBIO-781] fix: remove border on navigation drawer

---

src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1324
- Remove address in service card
- Add short description in service card
- Adjust service card style
- Change description in service detail dialog from shortDescription to longDescription
- Fix order summary card
-

[DBIO-1325] Enhance customer select service

---

src/common/lib/api/service-request.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1621
- Adjust endpoint for get staking service by customer
- n/a
- n/a

[DBIO-1621] Adjust endpoint for get staking service by customer

---

src/common/constants/error-messages.js
src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/deprecated/Upload.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/LandingPage/SignIn/index.vue

[https://blocksphere2020.atlassian.net/browse/DBIO-1316](url)
- implement error message to createEMR page, uploadEMR and signin
-

[DBIO-1316] feat: adapt page to apply error message file

---

src/common/lib/polkadot-provider/command/electronic-medical-record.js
src/router/routes/index.js
src/views/Dashboard/Customer/Home/Emr/Edit.vue
src/views/Dashboard/Customer/Home/Emr/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1566
- Add new edit EMR page.

[DBIO-1566] feat: new emr edit page.

---

src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1503
- Fix service detail dialog
-

Fix: fix staking list table

---

src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1531
- Add validation to push in step 1 page when refresh in request test flow
-

Fix: fix select service validation

---

src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1561
- fix/enhancement english alphabet
-

[DBIO-1561] fix: English alphabet

---

src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1561
- fix/enhancement english alphabet
-

[DBIO-1561] fix: Update fix english alphabet

---

src/common/lib/polkadot-provider/command/service-request.js
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue
tests/unit/views/Dashboard/Customer/Home/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1373
- Fix fetch items  in staking tab
- n/a
-n/a

[DBIO-1373] fix: unstaking button

---

.github/workflows/builder.yml
.github/workflows/deployer.yml
README.md

- https://blocksphere2020.atlassian.net/browse/DBIO-1656
- fix deployments conditional
-

[DBIO-1656] ci: fix deployments conditional

---

.github/workflows/builder.yml
.github/workflows/deployer.yml
.github/workflows/tester.yml
README.md

- https://blocksphere2020.atlassian.net/browse/DBIO-1565
- Add new deployment environment
-

Add new deployment environment

---

.github/workflows/analyzer.yml

- N/A
- Create code analyzer
-

Create code analyzer

---

src/views/Dashboard/Customer/Home/Emr/Edit.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1650
- Add tx weight above submit button
- Adjust edit EMR
-

[DBIO-1650] fix: adjust emr edit & add tx weight

---

tests/unit/common/components/file.spec.js

- [https://blocksphere2020.atlassian.net/browse/DBIO-1469](url)
- Add unit test file component
**Scope**
-

[DBIO-1469] Tests: Unit testing fle component

---

tests/unit/common/components/input.spec.js

- [https://blocksphere2020.atlassian.net/browse/DBIO-1474](url)
- Add unit test for input component
-

[DBIO-1474] Tests: unit testing input component

---

src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
tests/unit/views/Dashboard/Customer/Home/RequestTest/Checkout/index.spec.js
tests/unit/views/Dashboard/Customer/Home/RequestTest/Checkout/payment-checkout.spec.js
tests/unit/views/Dashboard/Customer/Home/RequestTest/lab-detail-card.spec.js
tests/unit/views/Dashboard/Customer/Home/RequestTest/pay-remaining-dialog.spec.js
tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-detail-card.spec.js
tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-receipt-dialog.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1581
- Adjust payment detail card
- Test payment detail card
- test checkout page
- test lab detail card
-

[DBIO-1581] tests: unit test checkout page

---

tests/unit/views/Dashboard/Customer/Home/RequestTest/request-test-form.spec.js
tests/unit/views/Dashboard/Customer/Home/RequestTest/select-location.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1579
- test select location
- test request test form
-

[DBIO-1579] tests: test select location

---

src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1776
- adjust layout unlock wallet 
-

[DBIO-1776] fix: adjust layout unlock wallet

---

src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1777
- Fix TxWeight number toFixed 4
-

[DBIO-1777] fix: TxWeight number toFixed 4

---

.github/workflows/deployer.yml
.github/workflows/dev-tmp.yml

- https://blocksphere2020.atlassian.net/browse/DBIO-1781
- add nodeSelector to deployment
-

[DBIO-1781] ci: add nodeSelector to deployment

---

src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
src/views/LandingPage/SelectRole/index.vue

- N/A
- Update redirect page after login
-

fix: Redirect page

---

tests/unit/views/Dashboard/Customer/Home/PaymentHistory/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1613
- unit testing payment history
-

[DBIO-1613] tests: payment history

---

src/common/lib/polkadot-provider/events/index.js
src/store/substrate/event-types.json

- https://blocksphere2020.atlassian.net/browse/DBIO-1774
- handle events index condition for unstake notification
-

[DBIO-1774] fix: handle events index condition

---

src/common/lib/api/index.js
src/common/lib/api/tx-hash.js
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1330
- add lib tx-hash
- post transaction hash from payment to database
-

[DBIO-1330] feat: post tx hash to database

---

src/common/lib/polkadot-provider/query/genetic-analysis.js
src/common/lib/polkadot-provider/query/genetic-analysts.js

- 
- there is error in lib/polkadot-provider/query genetic-analysis & genetic-analysts function
-

Fix: error in genetic analysis & genetic analysts

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
src/views/Dashboard/Customer/Layout.vue
src/views/Dashboard/GeneticAnalyst/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1871
- fix description length
- Update unlock wallet layout
-

[DBIO-1871] fix: Some issue with description and update layout

---

tests/unit/views/Dashboard/Customer/Home/home.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1574
- add unit testing for Customer home Dashboard
-

[DBIO-1574] Tests: unit testing customer DashBoard

---

src/common/lib/api/customer/genetic-analysis-order.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1876
- Change genetic analysis order API
-

[DBIO-1876] Fix: change genetic analysis order API

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/EmptyDataCard.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1743
- change debio-logo to defaultAvatar
-

[DBIO-1743] fix: change debio logo to defaultAvatar

---

src/common/lib/api/customer/genetic-analysis-order.js
src/common/lib/api/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1876
- Change genetic analysis order API (revise)
-

[DBIO-1876] Fix: Api genetic analysis order

---

src/common/lib/api/orders.js
src/common/styles/function.sass
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
tests/unit/views/Dashboard/Customer/Home/home.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1323
- Create button view to etherscan
-

[DBIO-1323] feat: Add button view to etherscan

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1739
- Remove button on step 3
- Update validation
-

refactor: Remove button on step 3 and update validation

---

src/common/lib/api/customer/genetic-analysis-order.js
src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1831
- https://blocksphere2020.atlassian.net/browse/DBIO-1876
- Filtering geneticAnalysis. if status Unpaid, cannot show in table (1831)
- change typo API on genetic analysis order (1876)
-

[DBIO-1831] Fix: Ceate Genetic Analysis lists Tab

---

src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue

- Genetic Anlysis list] Creat Descending sortir for Genetic Analysis list table
- create sorting table ascending base on last update (updatedAt)
- adjust style on table
-

[DBIO-1879] feat: add sort for genetic analysis list table.

---

tests/unit/views/Dashboard/Customer/Home/GeneticData/genetic-analysis-list.spec.js
tests/unit/views/Dashboard/Customer/Home/genetic-analyst-list.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1756
- Genetic analysis list page unit test.

[DBIO-1756] tests: genetic analysis list page.

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1739
- Minor update placeholder wording
- Fix button disabled
-

[DBIO-1739] fix: Minor fix button disabled and update placeholder wording

---

tests/unit/views/Dashboard/GeneticAnalyst/Account/index.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Home/index.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/layout.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1733
- Unit test genetic analyst dashboard.
- Unit test genetic analyst account dashboard.
- Unit test genetic analyst services dashboard.
- Unit test genetic analyst dashboard layout.

[DBIO-1733] tests: genetic analyst dashboard unit tests.

---

tests/unit/views/Dashboard/Customer/Home/GeneticData/add.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1755
- Add genetic data page unit test.

[DBIO-1755] tests: add genetic data page unit test.

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- N/A
- Fix Dynamic order accepted
-

fix: GA Dynamic order accepted

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1831
- enhance genetic analysis step4. order paid status automaticly change 
-

[DBIO-1831] Fix: order status GA step 4

---

src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1831
- enhance geneticAnalysisTab list table by make data realtime
-

[DBIO-1831] Chore: enhance genetic analysis tab list

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- N/A
- Add button loading
- Code improvement
-

fix: Add button loading and code improvement

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1885
- handle unloaded variable profileImage
-

[DBIO-1885] fix: update variable profile image not loaded

---

package-lock.json
package.json
src/common/components/Dialog/SuccessDialog.vue
src/common/components/Dialog/UploadingDialog.vue
src/common/lib/ipfs/crypt-worker/encrypt-worker-file.js
src/common/lib/pinata/index.js
src/common/lib/polkadot-provider/command/genetic-analysis-orders.js
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

[DBIO-1705] feat: pinata ipfs upload

---

src/common/lib/pinata/index.js
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

- implement @debionetwork/pinata-ipfs package
-

[DBIO-1705] feat: implement debionetwork-pinata-ipfs

---

src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

- N/A
- Fix IPFS error upload
- Remove trailing spaces
-

fix: IPFS error upload and remove trailing spaces

---

.github/workflows/builder.yml

- N/A
- change deployment env
-

ci: change deployment env

---

src/views/Dashboard/Customer/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1836
- fix wording
-

[DBIO-1836] Fix: fix some wording

---

src/common/lib/pinata/index.js
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- N/A
- Fix Array geneticLink download
-

fix: Array geneticLink download

---

src/common/lib/pinata/index.js
src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Details.vue
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/GeneticAnalyst/Home/index.vue
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- N/A
- Update IPFS (Pinata option) Metadata
- Update download issue
-

fix: IPFS download file type

---

src/common/components/File/index.vue
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
tests/unit/common/components/file.spec.js

- show uploaded file when edit
- add pop up when successfully updated gen data
- add tooltip to describe file
- adjust data type validation
-

[DBIO-1705] Fix: fix edit genetic data

---

src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/CheckoutPayment.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1873
- change wording popup dialog on genetic analysis step 3 after payment
- change default sorting on myGeneticAnalysisList table
-

[DBIO-1873] Fix: Change wording checkout payment GA loading dialog

---

src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

- N/A
- Fix Data response from downloading file
-

fix: Data response from downloading file

---

src/views/Dashboard/Customer/Home/GeneticData/Add.vue

- fix get file when edit gen data
-

[DBIO-1705] fix: fix get file when edit

---

src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

- Fix file type in upload/download 
-

[DBIO-1705] fix: fix file type

---

src/common/lib/pinata/index.js
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- n/a
- change decrypt downloaded file in ga
-

fix: fix downloading file in ga

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- N/A
- Update the file name using the file name when the user uploads
-

fix: minor update filename

---

src/common/lib/pinata/index.js

- N/A
- Pinata improvement feature
- Fix function notfound
-

fix : Pinata improvement feature

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

- N/A
- Fix File naming when re-upload file
-

fix: File naming when re-upload file

---

src/router/routes/customer.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/empty-data.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/information.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/select-service-analysis.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/success-page.spec.js
tests/unit/views/Dashboard/Customer/Home/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1798
- https://blocksphere2020.atlassian.net/browse/DBIO-1713
- https://blocksphere2020.atlassian.net/browse/DBIO-1746
- Add test success page
- Add unit testing request analysis
- Add unit test if empty data
- Add unit test select service 
- Add unit test information pop-up
- Add unit test analyst card
-

[DBIO-1798, DBIO-1713, DBIO-1746] tests: add unit test step 4 request analysis

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1810
- Fix button in navigation drawer
- Add Staking Id in staking service tab  
-

[DBIO-1810] feat: add staking id to staking service tab

---

src/views/LandingPage/GenerateAccount/SetPassword.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1974
- Fix recaptcha error.

fix: recaptcha sitekey.

---

.github/workflows/deployer.yml

cd: fix limit-rps error

---

src/views/LandingPage/SignIn/ChangePassword.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1974
- Fix Recaptcha on the change password page.

fix: recaptcha.

---

package-lock.json
package.json
src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue
src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
src/views/LandingPage/GenerateAccount/VerifyMnemonic/index.vue
src/views/LandingPage/GenerateAccount/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1669
- upgrade debio ui-components
- adjust wording on generate account
- change icon when successfully registered
-

[DBIO-1669] fix: enhance wording on generate account according to figma

---

src/store/substrate/index.js
src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue
src/views/Dashboard/Customer/Home/Emr/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1811
- Add loading on submit button
- Update redirect flow
-

[DBIO-1811] fix: EMR several issues

---

src/common/lib/api/customer/orders.js
src/common/lib/api/tx-hash.js
src/common/styles/function.sass
src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
tests/unit/common/components/dataTable/data-table.spec.js
tests/unit/views/Dashboard/Customer/Home/PaymentHistory/index.spec.js
tests/unit/views/Dashboard/Customer/Home/home.spec.js

- N/A
- merge main-tmp to main
-

merge main-tmp to main

---

src/common/components/Dialog/UploadingDialog.vue
src/common/lib/pinata/index.js
src/store/genetic-data.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1966
- add progress upload on pinata lib
- add cancel upload on pinata lib
- implement progress on add genetic data
-

[DBIO-1966] feat: add progress uploading in axios and implement to add genetic data

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1799
- add descending sort items by staking date on stake service tabel
- add descending sort items by order date on my test tabel 
-

[DBIO-1799] feat: create DSC sortir table list on "stake service" and "request test" 

---

.github/workflows/deployer.yml

- N/A
- optimize deployment resource request & limit
-

ci: optimize deployment resource request & limit

---

src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1669
- https://blocksphere2020.atlassian.net/browse/DBIO-2097
- change secret backup to mnemonic
- adjust wording on add genetic data file tooltip
-

[DBIO-1669, DBIO-2097] fix: fix wording on generate account & add genetic data

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/Information.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2090
- adjust styling and wording on important information pop up
-

[DBIO-2090] feat: update wording for important information pop up

---

src/common/styles/mixins.sass
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2089
- add new font on styles mixins
- add description of payment on payment card
-

[DBIO-2089] feat: update description in payment card

---

.maintain/install-hooks.sh
package.json

- https://blocksphere2020.atlassian.net/browse/DBIO-2155
- Git hooks.

feat: git hooks 

---

src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-ISSUE_NUMBER
- N/A
- Update get price
- Update column list
-

feat: Update column and price

---

src/views/Dashboard/Customer/Home/Emr/Create.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1811
- Update txWeight position
-

[DBIO-1811] refactor: EMR txWeight

---

src/common/lib/api/customer/orders.js
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue

- N/A
- Fix button view on etherscan
-

fix: View on etherscan

---

src/common/lib/api/customer/orders.js
src/common/lib/api/index.js
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2182
- https://blocksphere2020.atlassian.net/browse/DBIO-2174
- Update payment history data structure
-

feat: Update payment history with GA orders

---

src/views/Dashboard/Customer/Home/Emr/Create.vue

- N/A
- Minor fix stuck uploading
-

fix: EMR uploading

---

src/common/lib/pinata/index.js
src/common/lib/polkadot-provider/command/genetic-analysis-orders.js
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/CheckoutPayment.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/payment-card.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/service-analysis-card.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/success-page.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2184
- https://blocksphere2020.atlassian.net/browse/DBIO-2185
- https://blocksphere2020.atlassian.net/browse/DBIO-2193
- Adjust unpaid flow
- Adjust cancel flow
- Add unit testing for cards in request analysis flow
-

[DBIO-2184, DBIO-2185, DBIO-2193] fix: enhance unpaid and cancel flow on request anylisis

---

src/router/routes/customer.js
src/views/Dashboard/Customer/Home/GeneticData/Details/ReasonOfRejection.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/ServiceCard.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/index.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/reason-of-rejection.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/service-card.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/stepper-status-card.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2198
- https://blocksphere2020.atlassian.net/browse/DBIO-2199
- create ga order details page
- add unit test
-

[DBIO-2198, DBIO-2199] feat: create ga order details page

---

package-lock.json
src/common/components/Navbar.vue

- N/A
- fix debio balance in navbar
-

fix: fix debio balance in navbar

---

src/common/lib/pinata-proxy.js

- N/A
- fix error in uploadFile to Pinata
-

fix: error pinata

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2241
- fix card styling on select ga analysis service
-

[DBIO-2241] fix: styling on showing anlysis service (step 2)

---

src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1783
- change parameter order in createOrder extrinsics
- fix button on request test success page
-

[DBIO-1783] fix: adjust parameter on createOrder

---

src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue

- N/A
- adjust data on genetic data list
-

fix: error genetic data list

---

package-lock.json
package.json
src/common/components/Navbar.vue

- N/A
- upgrade polkadot-package version to 0.0.9 (tx weigh and getGeneticAnalystById fixed)
- fix signout button
-

fix: fix signout and upgrade polkadot-package version to 0.0.9

---

src/views/Dashboard/Customer/Home/GeneticData/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2225
- fix success pop up when successfully updated genetic data
-

fix: fix success pop up after edit genetic data

---

src/common/lib/polkadot-provider/command/service-request.js
src/common/lib/polkadot-provider/query/genetic-analysts-services.js
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2240
- https://blocksphere2020.atlassian.net/browse/DBIO-2379
- handle download ga result sample
- add query getAllGeneticAnalystServices
- fix stakingAmount by add command createRequest 
-

fix: download result sample & staking amount

---

.github/workflows/builder.yml
.github/workflows/dev-tmp.yml

- [DBIO-2387]
- ci: add new env
- 
[DBIO-2387]: https://blocksphere2020.atlassian.net/browse/DBIO-2387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: add new env

---

src/common/lib/polkadot-provider/query/genetic-analysis-orders.js
src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue
src/views/Dashboard/Customer/Home/Emr/index.vue
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/CheckoutPayment.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2346
- https://blocksphere2020.atlassian.net/browse/DBIO-2380
- TO ADJUST --> add queryGeneticAnalysisOrderById & queryLastGeneticAnalysisOrderByCustomer in library polkadot-provider
- fix tx weight on EMR
- fix tx weight on geneticData
- fix tx weight on requestAnalysisSerivice
- fix tx weight on serviceRequest
- fix error balance on checkout page
- removed unused lines
- TO ADJUST --> add queryGeneticAnalysisOrderById & queryLastGeneticAnalysisOrderByCustomer in library polkadot-provider

fix: fix rename function tx weight on customer-ui

---

src/common/lib/polkadot-provider/events/handlers/customer.js
src/store/substrate/event-types.json

- https://blocksphere2020.atlassian.net/browse/DBIO-1789
- https://blocksphere2020.atlassian.net/browse/DBIO-1788
- Fix Mismatch order notification
-

fix: Mismatch order notification

---

package-lock.json
package.json
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/ReasonOfRejection.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2185
- https://blocksphere2020.atlassian.net/browse/DBIO-2325
- https://blocksphere2020.atlassian.net/browse/DBIO-2345
- upgrade & adjust polkadot-provider
- add comparison of balance and tx weight on add ga data and create ga order pages
- add pop up in step 2 of request GA if customer has unpaid order
- adjust new styling and button on payment card
- enhance unpaid GA order from payment history
- fix tx weight on request test create-order
- N/A

fix: request analysis payment flow

---

src/common/lib/polkadot-provider/events/handlers/customer.js
src/store/substrate/event-types.json

- https://blocksphere2020.atlassian.net/browse/DBIO-2203
- enhance customer notification
-

fix: enhance customer notification

---

src/views/Dashboard/Customer/Home/GeneticData/Add.vue

- N/A
- fix error on add genetic data
- N/a

fix: fix bugs add genetic data

---

src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2423
- fix fetch genetic analysis list
- fix tabel styling
- n/a

fix: genetic analysis list tabel

---

src/views/Dashboard/Customer/Home/GeneticData/Details/ReasonOfRejection.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue

- N/A
- fix bugs in view detail ga
- ### WARNING ⚠️
- n/a

fix: fix details genetic analysis

---

src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue

- N/A
- Update refunded value
-

fix: Payment history Refunded value

---

src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1667
- update error password wording
-

fix: update error password wording

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2476
- fix: empty genetic data page
- fix: checkout ga order
-

fix: checkout ga order & empty genetic data page

---

src/common/lib/api/index.js

- N/A
- fix status general error from api
-

fix: fix status general error from api

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2481
- fix error styling on payment card
- n/a

fix: error on payment ga card

---

src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2430
- fix fetch on dashboard
- fix fetch on my test
- n/a

fix: fetch dashboard and my test

---

src/views/Dashboard/Customer/Home/GeneticData/Add.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2212
- fix button validation on add genetic data
- n/a

fix: button validation on add genetic data

---

src/common/components/Navbar.vue
src/router/routes/customer.js
src/store/substrate/index.js
src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/GeneticData/Result.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
src/views/Dashboard/Customer/Home/index.vue
tests/unit/views/Dashboard/Customer/Home/GeneticData/result.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2200
- create result page
- @ciniiia I just updated the balance formatting inside vuex, so you need to check these files. It's working as it should or not after I made that changes
```js
src\views\Dashboard\Customer\Home\GeneticData\Add.vue
src\views\Dashboard\Customer\Home\GeneticData\RequestAnalysis\AnalystDetail.vue
src\views\Dashboard\Customer\Home\GeneticData\RequestAnalysis\PaymentCard.vue
```

feat: Init view result analysis page

---

src/views/Dashboard/Customer/Home/MyTest/TestResult.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2496
- Minor update document previewer
-

fix: minor update layout

---

src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1403
- fix error on order rejection title & description
- fix prices format on reject detail dialog
- n/a

fix: wording and format price on rejected order details

---

src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1209
- fix download result sample button
- n/a

fix: download test result sample

---

src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue
src/views/Dashboard/Customer/Home/Emr/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2536
- fix couldn’t save the edited file unless we change the uploaded file
- fix doubled listing file after editing
-

fix: EMR several issues

---

src/views/Dashboard/Customer/Home/GeneticData/Result.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2540
- Fix pair public key
-

fix: GA test result decryption

---

src/common/lib/pinata-proxy.js
src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue

- N/A
- fix get ga public key
- fix function download on pinata-proxy (temp: download file on FE - to adjust later when the package update)
- n/a

fix: fix download ga result

---

src/common/lib/polkadot-provider/events/handlers/customer.js
src/store/substrate/event-types.json
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
tests/unit/views/Dashboard/Customer/Home/PaymentHistory/details.spec.js

- N/A
- Minor update wording notification
-

fix: Minor update wording notification

---

src/views/Dashboard/Customer/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1512
- fix rendering status and directing button on order list in dashboard
- n/a

fix: detail button on dashboard - recent test

---

src/router/routes/customer.js
src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1653
- Update router with params
- Get order data with id
- Fix blank page order detail page 
-

fix: Order detail blank page

---

tests/unit/views/Dashboard/Customer/Home/MyTest/test-result.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1676
- Add unit testing for test result page
- Need more unit test

tests: Add unit testing test result page

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/MyTest/ConfirmationDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2480
- https://blocksphere2020.atlassian.net/browse/DBIO-2490
- fix loading on pop up button
- fix scroll on detail pop up
-

fix: styling on pop up

---

src/views/LandingPage/GenerateAccount/SetPassword.vue
src/views/LandingPage/SignIn/ChangePassword.vue

- n/a
- fix: wording on password validation
- n/a

fix: wording on password validation

---

src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2522
- Update refunded value
-

fix: Refunded amount value

---

package-lock.json
package.json
src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
src/views/Dashboard/Customer/Home/GeneticData/GeneticAnalysisList.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
src/views/Dashboard/Customer/Home/GeneticData/Result.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2576
- Fix typo.
- Update polkadot provider package.

fix: typo and update polkadot provider

---

package-lock.json
src/common/components/Navbar.vue
src/common/lib/metamask/escrow.js
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/Success/PaymentSuccess.vue

- N/A
- adjust metmask address on payment request test
- N/A
https://drive.google.com/file/d/1b768Xehq6FD1S_KWlQHR2if0-gNM9n_0/view?usp=sharing

fix: bugs on request test

---

src/common/components/Navbar.vue
src/router/routes/customer.js
src/router/routes/index.js
src/views/Dashboard/Customer/Layout.vue
tests/unit/views/Dashboard/Customer/Home/PaymentHistory/details.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2612
- Refactor customer router path
- Update breadcrumb
-

refactor: Remove customer path

---

babel.config.js
package-lock.json
package.json
src/common/lib/ipfs/crypt-worker/decrypt-worker.js
src/common/lib/ipfs/crypt-worker/encrypt-worker-file.js
src/common/lib/ipfs/crypt-worker/encrypt-worker.js
src/common/lib/ipfs/ipfs-worker/ipfsWorker.js
src/common/lib/metamask/index.js
src/common/lib/metamask/wallet.js
src/main.js
src/store/ethereum/index.js
src/store/metamask/index.js
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Layout.vue
src/views/LandingPage/SignIn/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2625
- Delete and replace the right console
- Add babel plugin for remove console in production
-

refactor: Remove console in production

---

src/common/constants/status.js
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2534
- fix: staking list tab
- fix: coloring on recent test 
- n/a

fix: staking list and coloring on recent test

---

src/common/components/NavigationDrawer.vue
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/Emr/Details.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue
src/views/Dashboard/Customer/Home/Emr/index.vue
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/index.vue
src/views/Dashboard/Customer/Layout.vue
tests/unit/views/Dashboard/Customer/Home/Emr/details.spec.js
tests/unit/views/Dashboard/Customer/Home/PaymentHistory/details.spec.js
tests/unit/views/Dashboard/Customer/Home/PaymentHistory/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2536
- https://blocksphere2020.atlassian.net/browse/DBIO-2616
- https://blocksphere2020.atlassian.net/browse/DBIO-2619
- Add EMR skeleton loading files
- Add loading data table (EMR and Payment History)
- Update unit testing
- Update and Fix redundant route
-

fix: EMR edit and update component with loading/skeleton

---

src/views/Dashboard/Customer/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2615
- add loading in dashboard dataTable
-

feat: add loading in dashboard dataTable

---

src/common/lib/metamask/index.js
src/common/styles/mixins.sass
src/views/Dashboard/Customer/Layout.vue
src/views/LandingPage/GenerateAccount/index.vue
src/views/LandingPage/LandingPagePopUp.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1262
- https://blocksphere2020.atlassian.net/browse/DBIO-2634
- add pop up to switch network to mainet / testnet
- adjust layout styling on generate account
- n/a

feat: add switch network to mainet / testnet

---

src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue

- N/A
- Improve skeleton loading
- Improve button submit behavior
-

fix: Fix and improve EMR skeleton loading

---

src/common/lib/price-format.js
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/ServiceCard.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/StepperStatusCard.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/service-card.spec.js
tests/unit/views/Dashboard/Customer/Home/GeneticData/Details/stepper-status-card.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2620
- https://blocksphere2020.atlassian.net/browse/DBIO-2648
- fix error pop-up 
- on ServiceCard -> remove queryGeneticAnalystByAccountId, queryGeneticAnalystServicesByHashId, and, queryGeneticAnalysisOrderById. add props service
- on StepperStatusCard -> remove queryGeneticAnalysisOrderById, queryGeneticAnalysisByGeneticAnalysisTrackingId, queryGeneticAnalystByAccountId. add props analysis
- adjust unit test
- n/a

fix : Req ga

---

src/router/routes/generateAccount.js
src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
src/views/LandingPage/GenerateAccount/SetPassword.vue
src/views/LandingPage/SignIn/ChangePassword.vue
tests/unit/views/LandingPage/GenerateAccount/registration-successful.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2645
- fix wording, add params 'flag'
- fix unit test
- n/a

feat: wording on successfully  set / changed password page

---

src/common/lib/pinata-proxy.js
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/Emr/Create.vue
src/views/Dashboard/Customer/Home/Emr/Edit.vue
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
src/views/Dashboard/Customer/Home/MyTest/TestResult.vue
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2661
- Add file size to pinata metadata
- @azmimuhammad @ciniiia Please re-check this PR, help me to make sure everything's working as expected

feat: Add file size to metadata

---

.github/ISSUE_TEMPLATE/1.bug_report.yml

- https://blocksphere2020.atlassian.net/browse/DBIO-2444
- add issue template for bug report
-

feat: add issue template for bug report

---

src/views/Dashboard/Customer/Home/MyTest/OrderHistoryDetail.vue
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2617
- add loading on table
- add loading on my test detail page
- n/a

fix: add loading display on my test

---

src/common/lib/polkadot-provider/events/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2502
- Fix notification validation input
-

fix: Notification validation

---

src/common/lib/api/customer/labs.js
src/store/lab.js
src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2105
- feat: get all service available
- n/a

feat: get all service availble

---

src/router/routes/customer.js
src/views/Dashboard/Customer/Home/RequestTest/Canceled/OrderCanceled.vue
src/views/Dashboard/Customer/Home/RequestTest/Canceled/index.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2321
- enhance flow after cancel order
-

fix: flow cancel order

---

src/common/lib/polkadot-provider/events/handlers/customer.js
src/store/substrate/event-types.json

- https://blocksphere2020.atlassian.net/browse/DBIO-2482
- enhance notification for request test flow
-

feat: request test flow notification

---

src/common/lib/polkadot-provider/events/handlers/customer.js
src/common/lib/polkadot-provider/events/index.js
src/store/substrate/event-types.json

- https://blocksphere2020.atlassian.net/browse/DBIO-2482
- enhance request test flow notification
-

fix: enhance request test flow notification

---

src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2726
- add wording on generate acc
- n/a

feat: adjust wording on generate acc

---

src/store/substrate/event-types.json

- https://blocksphere2020.atlassian.net/browse/DBIO-2484
- add routes on GA notif
- remove labs on event-type.json
- n/a

fix: routes on notification

---

src/store/substrate/index.js

- N/A
- Update validation event
-

fix: Event not show

---

src/common/lib/pinata-proxy.js
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2747
- replace downloadWithProgress with downloadFile on analystServiceDetail
- Tech debt => Add download progress

fix: download file from pinata

---

.github/workflows/create-tags.yml

- N/A
- fix action permission
-

ci: fix action permission

---

package-lock.json
package.json
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2484
- update polkadot-provider
- fix condition on payment history detail 
-

fix: get txhash on payment history

---

.github/workflows/create-tags.yml

Reverts debionetwork/debio-customer-ui#514

ci: revert "fix action permission"

---

src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2681
- fix: adjust button on payment detail card
- n/a

feat: adjust button on payment detail - success

---

src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2745
- fix payment detail card for staking service flow
- n/a

fix: payment-detail-card

---

package.json
src/common/components/NavigationDrawer.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2674
- display app version
- @ciniiia @azmimuhammad Please check the new ENV I've made [here](https://blocksphere2020.atlassian.net/wiki/spaces/DBIO/pages/33063034/Frontend+ENV)

feat: display app version

---

package.json

chore: bump version to 2.1.5

---

src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue
src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2823
- remove switch network on global (layout.vue)
- trigger switch network on request test payment
- n/a

fix: switch network

---

src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2817
- update wording and styling on stake service page
- update wording and styling on stake agreement pop up
- add checkbox on stake agreement pop up
- n/a

feat: update phrase on stake service page and agreement pop up

---

src/views/Dashboard/Customer/Layout.vue

- N/A
- Minor update tooltips wording on drawer menu
-

fix: Minor wording update on tooltips menu

---

package-lock.json
package.json

- N/A
- bump version to 2.1.6
-

chore: bump version to 2.1.6

---

src/common/components/Dialog/LoadingDialog.vue
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2837
- 
-

fix: fix loading and proceed request

---

src/common/constants/error-messages.js
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2927
- fix validation when amount is 0
- add `AMOUNT`error message
-

fix: validation for 0 amount on staking agreement dialog

---

src/views/Dashboard/Customer/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2832
- fix GA orders not loaded properly
-

fix: GA orders not loaded

---

src/common/components/Navbar.vue
src/views/Dashboard/Customer/Layout.vue
src/views/LandingPage/SignIn/ChangePassword.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2649
- add clear account on sign out
- add clear account on change password
- n/a

feat: add clear account when sign out and change password

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2837
- fix pair address on get lastOrder
- fix remaing amount on payment detail card
- n/a

fix: bugs on get lastorder

---

src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2837
- fix: remaining staking amount in DBIO
- n/a

fix: remaining DBIO amount on sataking dialog

---

src/common/constants/status.js
src/common/lib/api/customer/conversion.js
src/common/lib/api/customer/debio-balance.js
src/common/lib/api/customer/index.js
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
tests/unit/views/Dashboard/Customer/Home/GeneticData/result.spec.js
tests/unit/views/Dashboard/Customer/Home/PaymentHistory/details.spec.js
tests/unit/views/Dashboard/Customer/Home/home.spec.js
tests/unit/views/Dashboard/Customer/Home/index.spec.js
tests/unit/views/Dashboard/Customer/Home/order-history-detail.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2896
- remove "DAI"
- implement dynamic converter 
- n/a

feat: implement dynamic converter

---

src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/Phr/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2929
- Revamp banner on My Test
- Revamp banner on My PHR
- n/a

feat: revamp banner

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2879
- change variable servicFlow to service_flow
- n/a

fix: service_flow on createOrder

---

src/common/styles/mixins.sass
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/CheckoutPayment.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SelectServiceAnalyst.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/SuccessPage.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/index.vue
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/RequestTest/Canceled/index.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/index.vue
src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/index.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/Success/index.vue
src/views/Dashboard/Customer/Home/RequestTest/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2972
- direct `view instruction` button to purchase kit link
- add link on service detail dialog
- add overflow scroll on description box in service detail dialog
- adjust menu card as per figma (add address and test category)
- add optional mark on request test form
- wording: change `service category` to `test category`
- wording: change `expected duration` to `maximum duration`
- wording: change `success` to `summary/instruction`
-

feat: apply unlimited description and purchase link available field

---

src/common/components/Navbar.vue
src/common/lib/api/customer/index.js
src/common/lib/api/customer/notifications.js
src/common/lib/notification.js
src/store/substrate/index.js
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2341
- https://blocksphere2020.atlassian.net/browse/DBIO-2949
- https://blocksphere2020.atlassian.net/browse/DBIO-2872
- add block to notification
- enhance get notification from backend
-

feat: enhance notification

---

src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2987
- fix request a service link
-

fix: request a service link

---

src/common/components/NavigationDrawer.vue
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2995
- add sidebar for menstrual calendar
- add route for menstrual calendar
-

feat: add sidebar for menstrual calendar

---

src/common/lib/utils/env.js
src/store/substrate/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2949
- fix logic on check notification
-

fix: bugs on store.connect

---

src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2969
- https://blocksphere2020.atlassian.net/browse/DBIO-3018
- https://blocksphere2020.atlassian.net/browse/DBIO-2972
- add skeleton-loader on payment card
- handle special character on customer
- fix bugs on purchase link/instruction
-

feat: add loadning skeleton on payment detail card

---

src/store/substrate/index.js

- https://blocksphere2020.atlassian.net/browse/DBIO-ISSUE_NUMBER
- N/A
- fix bugs
-

fix: bugs on customer

---

src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-ISSUE_NUMBER
- N/A
- change region to state
-

fix: change variable region to state

---

src/common/lib/notification.js
src/common/lib/string-format.js
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/
- dd fmtReferenceFromHex to string-format file
-

feat: add function formatReference to strin-format file

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2991
- fix breadcrumbs href
-

feat: fix breadcrumbs

---

src/common/lib/notification.js
src/store/substrate/index.js
src/views/Dashboard/Customer/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2341
- fix: fetch unlisted notification
-

fix: get unlisted notification

---

.github/workflows/deployer.yaml
.maintain/docker/entrypoint.sh
README.md

ci: cleanup ssh tunneling

---

src/common/components/Calendar.vue
src/common/components/Day.vue
src/common/components/DaySelectAverage.vue
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SubscriptionSetting.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

- fix vertical scroll hidden in menstrual calendar selection
- subscription settings
- https://blocksphere2020.atlassian.net/browse/DBIO-2993
- https://blocksphere2020.atlassian.net/browse/DBIO-3049

fix: menstrual calendar selection vertical scroll not visible & feat: subscription setting menstrual calendar

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SubscriptionSetting.vue

- change text modal subscription setting

fix: text modal subscription setting

---

src/common/components/Day.vue
src/common/constants/menstruation-moods.js
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/mockData.js
src/views/Dashboard/Customer/Layout.vue

- direct button menstrual calendar to maintanance page
- add logic for prediction, ovulation, and fertility calculation
- add function to get summary
https://blocksphere2020.atlassian.net/browse/DBIO-2994
https://blocksphere2020.atlassian.net/browse/DBIO-3052

feat: menstrual calendar dashboard

---

package-lock.json
package.json
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Layout.vue
src/views/Dashboard/maintenancePageLayout.vue

- upgrade version to 2.1.8
- add coming soon page
- https://blocksphere2020.atlassian.net/browse/DBIO-3059
- https://blocksphere2020.atlassian.net/browse/DBIO-3052

feat: add coming soon page and  bump version to 2.1.8

---

src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

-fix variable service category
n/a

fix: variabel service category

---

src/common/constants/menstruation-moods.js
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue

- fix summary on menstrual calendar

fix: today summary

---

src/store/substrate/index.js
src/views/Dashboard/Customer/Home/RequestTest/AgreementDialog.vue
src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

- add validation when staking service
-https://blocksphere2020.atlassian.net/browse/DBIO-3024

feat: staking validation

---

src/common/components/Calendar.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue

- optimize add and remove emoji render
- optimize calendar render

feat: Emoji calendar

---

src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue

- add region and country full name from API response to list service for service request selected
- https://blocksphere2020.atlassian.net/browse/DBIO-3090
must merge this branch from debio-backend https://github.com/debionetwork/debio-backend/pull/457 before merge this branch

add region and country name for selected service

---

src/common/components/Navbar.vue
src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue

- fix usdt on payment history detail
- fix bug on wallet
- https://blocksphere2020.atlassian.net/browse/DBIO-3089

fix: format usdt on payment history detail

---

src/common/lib/polkadot-provider/command/service-request.js
src/common/lib/polkadot-provider/query/service-request.js
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentReceiptDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-3139
- https://blocksphere2020.atlassian.net/browse/DBIO-2923

fix: proceed button & insufficient balance error

---

src/views/Dashboard/Customer/Home/RequestTest/NoLab.vue

- fix show success dialog when staking

fix: show success dialog

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2923
- https://blocksphere2020.atlassian.net/browse/DBIO-3043

fix: route after proceed

---

src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue

- change height and width container
- change height and width img
- https://blocksphere2020.atlassian.net/browse/DBIO-3149

fix: contanier service lab select

---

.github/workflows/cicd.yaml

Reverts debionetwork/debio-customer-ui#650

revert: bump google-github-actions/setup-gcloud from 0.6.2 to 1.0.0

---

src/common/components/Navbar.vue
src/store/substrate/index.js

- fix watch balance on navbar
- https://blocksphere2020.atlassian.net/browse/DBIO-3144

fix: watch wallet

---

src/common/constants/menstrual-symptoms-emoji.js
src/common/lib/polkadot-provider/command/menstrual-calendar.js
src/common/lib/polkadot-provider/query/menstrual-calendar.js
src/store/index.js
src/store/menstrual-calendar.js
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

- Add loading on menstrual calendar subscription button
- Adjust emoticons wording
- Connect substrate to calendar
- Adjust addMenstrualCycleLog
- Change month ui from dropdown to arrow button
- 
- https://blocksphere2020.atlassian.net/browse/DBIO-3113
- https://blocksphere2020.atlassian.net/browse/DBIO-3123
- https://blocksphere2020.atlassian.net/browse/DBIO-3146

feat: connecting menstrual calendar dashboard with substrate

---

src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- fix bugs on payment request test
- fix button shown on payment success page
- https://blocksphere2020.atlassian.net/browse/DBIO-3174
- https://blocksphere2020.atlassian.net/browse/DBIO-3178

fix: bugs on payment and adjust button

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

- change mens calendar payment to DBIO
- https://blocksphere2020.atlassian.net/browse/DBIO-3152

feat: change mens calendar payment to DBIO

---

src/common/components/Navbar.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
tests/unit/views/Dashboard/Customer/Home/RequestTest/payment-detail-card.spec.js

- fix balance in checkout payment
- add conversion in payment checkout
- https://blocksphere2020.atlassian.net/browse/DBIO-3140
- https://blocksphere2020.atlassian.net/browse/DBIO-3166

fix: balance customer page

---

src/common/components/Calendar.vue
src/common/components/Day.vue
src/common/lib/api/customer/index.js
src/common/lib/api/customer/menstrual-calendar.js
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue

- enhance add and update menstrual calendar cycle log

feat: enhance add and update menstrual calendar cycle log

---

src/common/constants/status.js
src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue

- add finalized on staking status list
- https://blocksphere2020.atlassian.net/browse/DBIO-3169

feat: add finalized on staking status list

---

src/common/components/Navbar.vue

- change link token "How to add balance" label

fix: change link tutorial token

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue

- diabled Subscription Setting button
- https://blocksphere2020.atlassian.net/browse/DBIO-3203

feat: diabled Subscription Setting button

---

src/common/components/Day.vue
src/common/components/Dialog/LoadingDialog.vue
src/common/lib/polkadot-provider/command/menstrual-calendar.js
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectEmoji.vue

- page for submit emoji
- connect to substrate
- https://blocksphere2020.atlassian.net/browse/DBIO-3173

feat: page for submit emoji and connect to substarte

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue

- fix mens date not shown 
- https://blocksphere2020.atlassian.net/browse/DBIO-3123

fix: mens date not shown

---

src/common/components/Calendar.vue
src/common/components/Day.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue

feat: enhance mens-calendar

---

src/common/components/Calendar.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectEmoji.vue

- fix, comment from jira link
- https://blocksphere2020.atlassian.net/browse/DBIO-3173

fix: emoji next and prev month

---

src/common/components/Calendar.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectEmoji.vue

fix: calendar

---

src/common/components/Calendar.vue
src/common/components/Day.vue

- fix select multiple dates when update

fix: select multiple  dates when update

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue

- fix error when update average cycle date

fix: error on average cycle date

---

src/common/components/Calendar.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue

fix: mens cycle calculation

---

src/common/components/Calendar.vue

fix: error on select-date

---

src/views/Dashboard/Customer/Home/Phr/index.vue

- remove undefined function (cause phr query substrate not called)
- https://blocksphere2020.atlassian.net/browse/DBIO-3192

fix: PHR added can't be displayed on table list

---

src/common/components/Calendar.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
src/views/Dashboard/Customer/Layout.vue

- fix  add last period when first subscribe

fix: add last period when first subscribe

---

src/common/components/Calendar.vue

- fix error multiple active strokeline in dashboard and select emoji

fix: multiple active strokeline

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue

- error on add mens cycle log (update flow)

fix: error on add mens cycle log

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

- fix insufficient balance for menstrual subscription
- https://blocksphere2020.atlassian.net/browse/DBIO-3222

fix: insufficient balance for menstrual subscription

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue

- countdown subscription in calendar
- https://blocksphere2020.atlassian.net/browse/DBIO-3209

feat: add countdown subscription in calendar

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

- coming soon label
- 8 number after point
- disabled button if not selected
- https://blocksphere2020.atlassian.net/browse/DBIO-3221

fix: coming soon label menstrual calendar landing page

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

- fix query menstrual subscription price list
- https://blocksphere2020.atlassian.net/browse/DBIO-3221

fix: query price menstrual subscription

---

src/common/components/Navbar.vue

- download keystore
- https://blocksphere2020.atlassian.net/browse/DBIO-3230

feat: export keystore

---

src/views/Dashboard/Customer/Home/RequestTest/MenuCard.vue

- remove uppercase on menu card
-https://blocksphere2020.atlassian.net/browse/DBIO-3246

fix: remove toUpperCase on menu card

---

src/assets/second-opinion-banner.svg
src/router/routes/customer.js
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/Banner.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
src/views/Dashboard/Customer/Layout.vue

- add second opinion menu and page (ui-only)
- fix checkout ga
- https://blocksphere2020.atlassian.net/browse/DBIO-3231
- https://blocksphere2020.atlassian.net/browse/DBIO-3199

feat: add second opinion and fix bugs

---

src/common/components/Navbar.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

- fix payment when no octopusAsset
- https://blocksphere2020.atlassian.net/browse/DBIO-3199

fix: payment when no octopusAsset

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue

- fix staking not show
- add loading
- https://blocksphere2020.atlassian.net/browse/DBIO-3186

fix: staking tab

---

src/common/components/Navbar.vue
src/common/constants/menstruation-moods.js
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue

- fix typos on summary
- add condition when user don't have any octopusAsset
- add request form
- https://blocksphere2020.atlassian.net/browse/DBIO-3268
-https://blocksphere2020.atlassian.net/browse/DBIO-3266

fix: typos on summary component

---

src/common/components/Navbar.vue

- fix: assign assetId 
- https://blocksphere2020.atlassian.net/browse/DBIO-3199

fix: reassign assetId

---

src/common/lib/polkadot-provider/query/genetic-analysis-orders.js
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue

- adjust import queryGeneticAnalysisOrderById from polkadot lib in FE to polkadot-provider
- remove queryGeneticAnalysisOrderById on polkadot lib
- https://blocksphere2020.atlassian.net/browse/DBIO-2789

fix: adjust queryGeneticAnalysisOrderById from polkadot lib in FE to polkadot-provider

---

src/views/Dashboard/Customer/Home/Phr/SecondOpinion/Banner.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/dummyRequestedOpinionList.json
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue

- add dummy data
- adjust some wording
- https://blocksphere2020.atlassian.net/browse/DBIO-3231

feat: adjust some wording and add dummy data

---

src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue

- adjust new wording on install polkadot pop up
- https://blocksphere2020.atlassian.net/browse/DBIO-3264

feat: adjust new wording on install polkadot pop up

---

src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue

- fix: install polkadot pop up width
- https://blocksphere2020.atlassian.net/browse/DBIO-3264

fix: install polkadot width

---

src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

fix: insufficient balance and wording message

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SubscriptionSetting.vue

DBIO-3198/SubscriptionSettings

---

src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

-adjustment layout request service
-https://blocksphere2020.atlassian.net/browse/DBIO-3179

fix: adjustment layout

---

src/views/Dashboard/Customer/Home/RequestTest/LabDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue
tests/unit/views/Dashboard/Customer/Home/RequestTest/lab-detail-card.spec.js

- fix website layout
- https://blocksphere2020.atlassian.net/browse/DBIO-3179

fix: layout card detail service

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

fix: promo text scratch

---

src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

fix: insufficient ballance in checkout order

---

src/views/Dashboard/Customer/Home/MyTest/index.vue

fix: change button color

---

src/common/lib/api/customer/myriad.js
src/common/lib/polkadot-provider/command/second-opinion.js
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue

- fix api for myriad connections
- https://blocksphere2020.atlassian.net/browse/DBIO-3248
- https://blocksphere2020.atlassian.net/browse/DBIO-3303

fix: fix and adjust myriad api connection

---

src/views/Dashboard/Customer/Home/MyTest/index.vue

fix: Issue on doubling add as bounty

---

src/common/components/Navbar.vue

fix: AddInstructionLink

---

src/common/lib/api/customer/myriad.js
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue

- fix error loading on register before create post
- https://blocksphere2020.atlassian.net/browse/DBIO-3303

fix: error register and auth before create post

---

src/common/components/Dialog/ConfirmationDialog.vue
src/common/components/Navbar.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Detail.vue

fix: add tooltip and adjust margin

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

fix: Adjust some word and display on Menstrual Calendar

---

src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
src/views/Dashboard/Customer/Layout.vue

- change myriad link
- https://blocksphere2020.atlassian.net/browse/DBIO-3248

fix: change redirect link

---

src/router/routes/customer.js
src/views/Dashboard/Customer/Home/Phr/Create.vue
src/views/Dashboard/Customer/Home/Phr/Edit.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/Banner.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/GrantAccessPHR.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue
src/views/Dashboard/Customer/Home/Phr/index.vue
src/views/Dashboard/Customer/Layout.vue

fix: changing name from PHR to health record

---

src/views/LandingPage/GenerateAccount/SetPassword.vue
src/views/LandingPage/SignIn/ChangePassword.vue
src/views/LandingPage/SignIn/InputMnemonic.vue

- fix popup
- https://blocksphere2020.atlassian.net/browse/DBIO-3329

fix: popup dashboard

---

src/views/NoAccessMobile.vue

- change wording on mobile view
- https://blocksphere2020.atlassian.net/browse/DBIO-3111

feat: enhance view for mobile access

---

src/views/Dashboard/Customer/Layout.vue

- fix error login popup not show
- https://blocksphere2020.atlassian.net/browse/DBIO-3329

fix : fix popup dashboard

---

src/views/Dashboard/Customer/Home/RequestTest/RequestTestForm.vue

fix: Change wording on default selected to any

---

src/views/LandingPage/Layout.vue

- Add Wording and link redirect to Debio.Network
https://blocksphere2020.atlassian.net/browse/DBIO-3328

feat: Wording and link to redirect Debio.NetWork

---

src/common/components/Navbar.vue

- Change Wording into Bride $DBIO from $NEAR
https://blocksphere2020.atlassian.net/browse/DBIO-3317

fix: Wording Bridge $DBIO in wallet

---

src/App.vue
src/common/lib/api/customer/myriad.js
src/views/NoAccessMobile.vue

- enhance mobile view
- https://blocksphere2020.atlassian.net/browse/DBIO-3111

fix: enhance mobile view

---

src/common/components/Navbar.vue
src/views/Dashboard/Customer/Home/Phr/Edit.vue
src/views/Dashboard/Customer/Home/index.vue
src/views/Dashboard/Customer/Layout.vue

- Change Link on Bridge
- Change Wording to Health Record without s
https://blocksphere2020.atlassian.net/browse/DBIO-3321
https://blocksphere2020.atlassian.net/browse/DBIO-3317

fix: Change Wording and Error 

---

src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue

- fix update mens calendar in new subscription 
- add mens calendar in payment history
- https://blocksphere2020.atlassian.net/browse/DBIO-3274
- https://blocksphere2020.atlassian.net/browse/DBIO-3293

feat: enhance menstrual subscription

---

src/common/lib/api/customer/myriad.js
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue

- remove API register visibility timeline
- N/A

remove: registerVisibilityTimeline

---

src/views/Dashboard/Customer/Home/PaymentHistory/Details.vue

- fix menstrual subscription payment detail
- 
- https://blocksphere2020.atlassian.net/browse/DBIO-3293

feat: add menstrual subscription payment detail

---

src/common/components/Day.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectMenstrualCalendar.vue

- fix mens calendar
- https://blocksphere2020.atlassian.net/browse/DBIO-3274

feat: fix mens calendar

---

src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue

- change geneticDataIds to electronicMedicalRecordIds
!! This PR is blocked by https://blocksphere2020.atlassian.net/browse/DBIO-3336

fix: change field geneticDataIds to emrDataIds

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SubscriptionSetting.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue
src/views/Dashboard/Customer/Home/RequestTest/SelectServicePage/SelectService.vue
src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

- fix issue on DBIO-3273 not using query params link
- change subscription setting using createdAt
https://blocksphere2020.atlassian.net/browse/DBIO-3273
https://blocksphere2020.atlassian.net/browse/DBIO-3198

fix: fix missing button and change startdate using createdAt

---

src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue

- add download phr files
- add decrypt phr files
- add upload phr files

feat: add download, decrypt and upload phr files

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

change route to payment checkout
https://blocksphere2020.atlassian.net/browse/DBIO-3273

fix: change from step 4 to step 3 stacking service

---

src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue

fix: format post to myriad

---

src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue

- fix upload file
- adjust wordings
- fix fetch electronicMedicalRecords

fix: upload file type

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SubscriptionSetting.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

- remove piled up button on step 3 request stack service
- adjust date on active date and inqueuedate
https://blocksphere2020.atlassian.net/browse/DBIO-3273
https://blocksphere2020.atlassian.net/browse/DBIO-3322

fix: piled up button on stack service and menstrual calender date

---

src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/index.vue

- fix description on second opinion
- change items on second opinion table sorts behaviours

fix: description on second opinion

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SelectEmoji.vue

- fix createdAt date format in updateMenstrualCycleLog
- N/A

fix: date format when update mens cycle log

---

src/common/lib/api/customer/myriad.js
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue

feat: handle enter on description symptom
- N/A

feat: handle enter on description symptom

---

src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/SubscriptionSetting.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue

fix: subscription typo

---

src/common/components/Dialog/SuccessDialog.vue
src/common/components/Dialog/UploadingDialog.vue
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/index.vue
src/views/Dashboard/Customer/Home/PaymentHistory/index.vue
src/views/Dashboard/Customer/Home/Phr/Create.vue
src/views/Dashboard/Customer/Home/Phr/Edit.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/Banner.vue
src/views/Dashboard/Customer/Home/Phr/MenstrualCalendar/index.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/Banner.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/GrantAccessPHR.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/index.vue
src/views/Dashboard/Customer/Home/RequestTest/Checkout/PaymentCheckout.vue
src/views/Dashboard/Customer/Home/index.vue
src/views/Dashboard/Customer/Layout.vue

fix: message

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue

fix an issue with users being unable to retrieve unstaked amoutn after 6 days had passed

fix:user cant retrieve unstaked amount

---

src/views/Dashboard/Customer/Home/MyTest/index.vue

fix: handle unstaked amount retrieval

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue

fix: add quality control price to genetic analysis order

---

src/common/lib/ipfs/crypt-worker/encrypt-worker-file.js
src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue

fix: stringify data before uploading

---

src/views/Dashboard/Customer/Home/GeneticData/Result.vue

fix: Download Genetic Analysis Report

---

src/views/Dashboard/Customer/Home/MyTest/TestResult.vue

fix: lab download

---

package-lock.json
src/common/components/Dialog/DownloadingDialog.vue
src/views/Dashboard/Customer/Home/MyTest/TestResult.vue

Fix: add downloading dialog modal

fix: adjustment on downloading dialog test result

---

src/common/lib/api/customer/myriad.js
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue

fix: select timeline when post to myriad

---

src/common/lib/api/customer/myriad.js
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/ConnectingPage.vue
src/views/Dashboard/Customer/Home/Phr/SecondOpinion/RequestPage/GrantAccessPHR.vue

fix: redirect to myriad

---

src/views/Dashboard/Customer/Home/GeneticData/index.vue
src/views/Dashboard/Customer/Home/MyTest/index.vue
src/views/Dashboard/Customer/Home/index.vue

fix: crash issue with ui components

---

src/views/Dashboard/Customer/Home/Phr/index.vue

Fix crash caused by ui components

fix: crash caused by ui components

---

src/views/Dashboard/Customer/Home/RequestTest/ServiceDetailDialog.vue

Temporarily revert change in url parser (The commented line to be fixed)
Revert #926

revert: parse url in description

---

src/common/lib/pinata-proxy.js
src/views/Dashboard/Customer/Home/MyTest/TestResult.vue

fix: download test file

---

src/views/Dashboard/Customer/Home/MyTest/TestResult.vue

fix: chunks progress in download

---

src/views/LandingPage/GenerateAccount/SetPassword.vue
src/views/LandingPage/SignIn/ChangePassword.vue

fix: some special character not accepted in password field

---

src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/RequestTest/PaymentDetailCard.vue

fix: payment

---

src/common/components/Navbar.vue
src/common/lib/price-format.js

fix: USDT Format issue

---

src/views/Dashboard/Customer/Home/GeneticData/Add.vue
src/views/Dashboard/Customer/Home/GeneticData/Details/index.vue
src/views/Dashboard/Customer/Home/GeneticData/GeneticDataList.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/AnalystDetail.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/PaymentCard.vue
src/views/Dashboard/Customer/Home/GeneticData/RequestAnalysis/ServiceAnalysisCard.vue

fix: issue with genetic analysis list not showing properly

---

src/views/Dashboard/Customer/Home/MyTest/StakingServiceTab.vue

fix: price formatting
